export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';

export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';
export const ORDER_COUNTRIES_ALF = 'ORDER_COUNTRIES_ALF';
export const ORDER_COUNTRIES_POP = 'ORDER_COUNTRIES_POP';
export const FILTER_BY_ACTIVITIES = 'FILTER_BY_ACTIVITIES';
export const GET_COUNTRIES_QUERY = 'GET_COUNTRIES_QUERY';